export const STATE = {
  APP: 'app',
  DATA: 'data',
  EDM: 'edm',
  ORGANIZATION: 'organization',
  PEOPLE: 'people',
  PERSON: 'person',
  WORKSITES: 'worksites',
  WORK_SCHEDULE: 'workSchedule',
};

// App

export const APP = {
  ACTIONS: 'actions',
  APP: 'app',
  ENTITY_SETS_BY_ORG: 'entitySetsByOrganization',
  FQN_TO_ID: 'fqnsToEntitySetIds',
  INITIALIZE_APPLICATION: 'initializeApplication',
  ERRORS: 'errors',
  ORGS: 'organizations',
  REQUEST_STATE: 'requestState',
  SELECTED_ORG_ID: 'selectedOrganizationId',
  SELECTED_ORG_TITLE: 'selectedOrganizationTitle',
  SWITCH_ORGANIZATION: 'switchOrganization',
};

/* People */

export const PEOPLE = {
  ACTIONS: 'actions',
  ADD_PARTICIPANT: 'addParticipant',
  COURT_TYPE_BY_PARTICIPANT: 'courtTypeByParticipant',
  CURRENT_DIVERSION_PLANS_BY_PARTICIPANT: 'currentDiversionPlansByParticipant',
  ENROLLMENT_BY_PARTICIPANT: 'enrollmentByParticipant',
  ERRORS: 'errors',
  GET_COURT_TYPE: 'getCourtType',
  GET_DIVERSION_PLANS: 'getDiversionPlans',
  GET_ENROLLMENT_STATUSES: 'getEnrollmentStatuses',
  GET_HOURS_WORKED: 'getHoursWorked',
  GET_INFRACTIONS: 'getInfractions',
  GET_PARTICIPANTS: 'getParticipants',
  HOURS_WORKED: 'hoursWorked',
  INFRACTIONS_BY_PARTICIPANT: 'infractionsByParticipant',
  INFRACTION_COUNTS_BY_PARTICIPANT: 'infractionCountsByParticipant',
  PARTICIPANTS: 'participants',
  REQUEST_STATE: 'requestState',
};

/* Person */

export const PERSON = {
  ACTIONS: 'actions',
  ADDRESS: 'address',
  ADD_INFRACTION_EVENT: 'addInfractionEvent',
  ADD_NEW_DIVERSION_PLAN_STATUS: 'addNewDiversionPlanStatus',
  ADD_NEW_PARTICIPANT_CONTACTS: 'addNewParticipantContacts',
  ADD_ORIENTATION_DATE: 'addOrientationDate',
  ADD_TO_AVAILABLE_CHARGES: 'addToAvailableCharges',
  ADD_WORKSITE_PLAN: 'addWorksitePlan',
  ALL_DIVERSION_PLANS: 'allDiversionPlans',
  ALL_PARTICIPANT_CASES: 'allParticipantCases',
  CHARGES: 'charges',
  CHARGES_FOR_CASE: 'chargesForCase',
  CHECK_INS_BY_APPOINTMENT: 'checkInsByAppointment',
  CHECK_IN_FOR_APPOINTMENT: 'checkInForAppointment',
  CREATE_NEW_ENROLLMENT: 'createNewEnrollment',
  CREATE_WORK_APPOINTMENTS: 'createWorkAppointments',
  DELETE_APPOINTMENT: 'deleteAppointment',
  DIVERSION_PLAN: 'diversionPlan',
  EDIT_APPOINTMENT: 'editAppointment',
  EDIT_CHECK_IN_DATE: 'editCheckInDate',
  EDIT_ENROLLMENT_DATES: 'editEnrollmentDates',
  EDIT_PARTICIPANT_CONTACTS: 'editParticipantContacts',
  EDIT_PERSON_CASE: 'editPersonCase',
  EDIT_PERSON_DETAILS: 'editPersonDetails',
  EDIT_PERSON_NOTES: 'editPersonNotes',
  EDIT_PLAN_NOTES: 'editPlanNotes',
  EDIT_REQUIRED_HOURS: 'editRequiredHours',
  EDIT_SENTENCE_DATE: 'editSentenceDate',
  EDIT_WORKSITE_PLAN: 'editWorksitePlan',
  EMAIL: 'email',
  ENROLLMENT_STATUS: 'enrollmentStatus',
  ERRORS: 'errors',
  GET_ALL_PARTICIPANT_INFO: 'getAllParticipantInfo',
  GET_APPOINTMENT_CHECK_INS: 'getAppointmentCheckIns',
  GET_CASE_INFO: 'getCaseInfo',
  GET_CHARGES: 'getCharges',
  GET_CHARGES_FOR_CASE: 'getChargesForCase',
  GET_CONTACT_INFO: 'getContactInfo',
  GET_ENROLLMENT_FROM_DIVERSION_PLAN: 'getEnrollmentFromDiversionPlan',
  GET_ENROLLMENT_STATUS: 'getEnrollmentStatus',
  GET_INFO_FOR_EDIT_CASE: 'getInfoForEditCase',
  GET_INFO_FOR_EDIT_PERSON: 'getInfoForEditPerson',
  GET_INFRACTION: 'getInfraction',
  GET_INFRACTION_TYPES: 'getInfractionTypes',
  GET_JUDGES: 'getJudges',
  GET_JUDGE_FOR_CASE: 'getJudgeForCase',
  GET_PARTICIPANT: 'getParticipant',
  GET_PARTICIPANT_ADDRESS: 'getParticipantAddress',
  GET_PARTICIPANT_CASES: 'getParticipantCases',
  GET_PROGRAM_OUTCOME: 'getProgramOutcome',
  GET_REQUIRED_HOURS: 'getRequiredHours',
  GET_WORKSITE_PLANS: 'getWorksitePlans',
  GET_WORKSITE_PLAN_STATUSES: 'getWorksitePlanStatuses',
  GET_WORK_APPOINTMENTS: 'getWorkAppointments',
  INFRACTION_EVENT: 'infractionEvent',
  INFRACTIONS_INFO: 'infractionsInfo',
  INFRACTION_TYPE: 'infractionType',
  INFRACTION_TYPES: 'infractionTypes',
  JUDGE: 'judge',
  JUDGES: 'judges',
  JUDGES_BY_CASE: 'judgesByCase',
  MARK_DIVERSION_PLAN_AS_COMPLETE: 'markDiversionPlanAsComplete',
  PARTICIPANT: 'participant',
  PERSON_CASE: 'personCase',
  PHONE: 'phone',
  PROGRAM_OUTCOME: 'programOutcome',
  REASSIGN_JUDGE: 'reassignJudge',
  REMOVE_CHARGE_FROM_CASE: 'removeChargeFromCase',
  REQUEST_STATE: 'requestState',
  REQUIRED_HOURS: 'requiredHours',
  UPDATE_HOURS_WORKED: 'updateHoursWorked',
  VIOLATIONS: 'violations',
  WARNINGS: 'warnings',
  WORKSITES_BY_WORKSITE_PLAN: 'worksitesByWorksitePlan',
  WORKSITE_PLANS: 'worksitePlans',
  WORKSITE_PLAN_STATUSES: 'worksitePlanStatuses',
  WORK_APPOINTMENTS_BY_WORKSITE_PLAN: 'workAppointmentsByWorksitePlan',
};

/* Work Schedule */

export const WORK_SCHEDULE = {
  ACTIONS: 'actions',
  APPOINTMENTS: 'appointments',
  DELETE_APPOINTMENT: 'deleteAppointment',
  FIND_APPOINTMENTS: 'findAppointments',
  GET_WORKSITE_AND_PERSON_NAMES: 'getWorksiteAndPersonNames',
  REQUEST_STATE: 'requestState',
  PERSON_BY_APPOINTMENT_EKID: 'personByAppointmentEKID',
  WORKSITE_NAMES_BY_APPOINTMENT_EKID: 'worksiteNamesByAppointmentEKID',
};

/* Worksites (and organizations) */

export const WORKSITES = {
  ACTIONS: 'actions',
  ADD_ORGANIZATION: 'addOrganization',
  ADD_WORKSITE: 'addWorksite',
  ERRORS: 'errors',
  GET_ORGANIZATIONS: 'getOrganizations',
  GET_WORKSITES: 'getWorksites',
  GET_WORKSITES_BY_ORG: 'getWorksitesByOrg',
  GET_WORKSITE_PLANS: 'getWorksitePlans',
  REQUEST_STATE: 'requestState',
  ORGANIZATION_STATUSES: 'organizationStatuses',
  ORGANIZATIONS_LIST: 'organizationsList',
  WORKSITES_BY_ORG: 'worksitesByOrg',
  WORKSITES_INFO: 'worksitesInfo',
  WORKSITES_LIST: 'worksitesList',
};
