// flow-typed signature: 45c8d073e9a02b007a342502bc406c2d
// flow-typed version: <<STUB>>/file-saver_v2.0.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-saver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-saver' {
  declare module.exports: any;
}
