// flow-typed signature: 9618d74a2614ef61710b2c2d87bc73d3
// flow-typed version: <<STUB>>/react-vis_v1.11.7/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vis' {
  declare module.exports: any;
}
