// @flow
import { Colors } from 'lattice-ui-kit';

const {
  GREEN,
  MAGENTA,
  ORANGE,
  PURPLE,
  RED,
} = Colors;

const ENROLLMENT_STATUS_COLORS = {
  ACTIVE: GREEN.G300,
  ACTIVE_REOPENED: GREEN.G300,
  AWAITING_CHECKIN: MAGENTA.M300,
  AWAITING_ORIENTATION: ORANGE.O300,
  COMPLETED: PURPLE.P300,
  JOB_SEARCH: GREEN.G300,
  REMOVED_NONCOMPLIANT: RED.R300,
  SUCCESSFUL: PURPLE.P300,
  UNSUCCESSFUL: RED.R300,
};

/* eslint-disable import/prefer-default-export */
export {
  ENROLLMENT_STATUS_COLORS,
};
