
import { APP_TYPE_FQNS } from './FullyQualifiedNames';

export const APP_TYPE_FQN_STRINGS = {
  APP_SETTINGS: APP_TYPE_FQNS.APP_SETTINGS.toString(),
  APPEARS_IN: APP_TYPE_FQNS.APPEARS_IN.toString(),
  APPOINTMENT: APP_TYPE_FQNS.APPOINTMENT.toString(),
  ASSESSED_BY: APP_TYPE_FQNS.ASSESSED_BY.toString(),
  CHARGED_WITH: APP_TYPE_FQNS.CHARGED_WITH.toString(),
  CONTACT_INFO_GIVEN: APP_TYPE_FQNS.CONTACT_INFO_GIVEN.toString(),
  CONTACT_INFORMATION: APP_TYPE_FQNS.CONTACT_INFORMATION.toString(),
  COURT_PRETRIAL_CASES: APP_TYPE_FQNS.COURT_PRETRIAL_CASES.toString(),
  EDITED_BY: APP_TYPE_FQNS.EDITED_BY.toString(),
  JUDGES: APP_TYPE_FQNS.JUDGES.toString(),
  LOCATION: APP_TYPE_FQNS.LOCATION.toString(),
  MANUAL_PRETRIAL_CASES: APP_TYPE_FQNS.MANUAL_PRETRIAL_CASES.toString(),
  MANUAL_SENTENCES: APP_TYPE_FQNS.MANUAL_SENTENCES.toString(),
  ORGANIZATION: APP_TYPE_FQNS.ORGANIZATION.toString(),
  PEOPLE: APP_TYPE_FQNS.PEOPLE.toString(),
  PROGRAM_OUTCOME: APP_TYPE_FQNS.PROGRAM_OUTCOME.toString(),
  REGISTERED_FOR: APP_TYPE_FQNS.REGISTERED_FOR.toString(),
  REMINDER_SENT: APP_TYPE_FQNS.REMINDER_SENT.toString(),
  SENTENCE_TERM: APP_TYPE_FQNS.SENTENCE_TERM.toString(),
  SENTENCED_WITH: APP_TYPE_FQNS.SENTENCED_WITH.toString(),
  SENTENCES: APP_TYPE_FQNS.SENTENCES.toString(),
  STAFF: APP_TYPE_FQNS.STAFF.toString(),
  WORKS_AT: APP_TYPE_FQNS.WORKS_AT.toString(),
  WORKSITE: APP_TYPE_FQNS.WORKSITE.toString(),
};
