// @flow

const NEW_PARTICIPANTS_COLUMNS = ['', 'NAME', 'SENT. DATE', 'CHECK-IN DEADLINE', 'REQ. HRS.'];
const PENDING_PARTICIPANTS_COLUMNS = ['', 'NAME', 'SENT. DATE', 'REQ. HRS.', ' '];
const VIOLATIONS_WATCH_COLUMNS = ['', 'NAME', '# OF VIO.', 'HRS. SERVED', ' '];

const TAGS = {
  REVIEW: 'Review',
  REPORT: 'Report',
};

export {
  NEW_PARTICIPANTS_COLUMNS,
  PENDING_PARTICIPANTS_COLUMNS,
  TAGS,
  VIOLATIONS_WATCH_COLUMNS,
};
